config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get 'venues/:id/view' => 'venues#view', as: :venue_view
  post 'venues/:id/available' => 'venues#available', as: :venue_available
  get 'venues/:id/make_reservation' => 'venues#make_reservation',
      as: :venue_make_reservationget
  post 'venues/:id/make_reservation' => 'venues#make_reservation',
       as: :venue_make_reservation

  get 'venues/:id/make_unpaid_reservation' => 'venues#make_unpaid_reservation',
      as: :venue_make_unpaid_reservationget
  post 'venues/:id/make_unpaid_reservation' => 'venues#make_unpaid_reservation',
       as: :venue_make_unpaid_reservation

  get 'venues/:id/court_price_at' => 'venues#court_price_at',
      as: :court_price_at
  get 'venues/:id/manage_venue' => 'venues#courts_and_prices',
      as: :courts_and_prices

  post '/search' => 'pages#search', as: :search
  get '/search' => 'pages#search', as: :searchget

  get "search_venues" => "search#show", as: :search_venues
  get 'venues/:id/cancelled_reservations' => 'venues#cancelled_reservations', as: :venue_cancelled_reservations



  get 'venues/:id/memberships' => 'venues#memberships', as: :memberships

  get 'users/:id/invoices' => 'users#invoices', as: :user_invoices

  root 'pages#home'

  get '/search' => 'pages#search'
  post '/search' => 'pages#search'

  namespace :api do
    post 'authenticate' => 'auth#authenticate'
    get '/auth/facebook' => 'auth#facebooklogin'
    get "sort_by_sport" => "venues#sort_by_sport"
    resources :users, only: [:create, :update] do
      get 'game_pass_check'

      collection do
        post :confirm_account
        post :reset_password
      end
    end
    resources :companies, only: [] do
      post 'send_support_email'
    end
    get 'search' => 'venues#search'
    get 'all_sport_names' => 'venues#all_sport_names'
    resources :cards, only: [:create, :index]
    resources :reservations, only: [:create, :index, :destroy]
    resources :subscriptions, only: [:index]
    resources :venues, only: [:show, :index] do
      get 'users'
      get 'utilization_rate'
      get 'available_courts'
    end
    resources :game_passes, only: [:index, :show, :create, :update, :destroy] do
      collection do
        get :court_sports
        get :court_types
        get :templates
        get :available
      end
    end
  end

  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'

  devise_for :admins,
             controllers: { confirmations: 'confirmations' }

  devise_for  :users,
              path: '',
              path_names: { sign_in: 'login',
                            sign_out: 'logout',
                            edit: 'profile' },
              controllers: { omniauth_callbacks: 'omniauth_callbacks',
                             registrations: 'registrations',
                             confirmations: 'confirmations' }

  devise_scope :user do
    patch '/users/confirm' => 'confirmations#confirm',
          as: :user_confirm
    patch 'users/update_password' => 'registrations#update_password'
  end

  devise_scope :admin do
    patch '/admins/confirm' => 'confirmations#confirm',
          as: :admin_confirm
    authenticate :admin, lambda { |admin| admin.god? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  resources :users, only: [:show] do
    post 'add_card' => 'stripe#add_card', as: :add_card
    post 'card_reminder'
    post 'assign_discount', as: :assign_discount
    get  'recurring_reservations', on: :member
  end

  resources :companies do
    resources :admins, expect: [:new, :show]
    get :reports
    post :create_report
    get :report
    resources :invoices do
      collection do
        post :create_drafts
        post :send_all
        post :mark_paid
        post :destroy_all
        post :create_report
      end
    end
    get 'revenue' => 'dashboard#revenue', as: :revenue
    get 'resv' => 'dashboard#resv'
    member do
      post 'import_customers'
      get  'customers_csv_template'
    end
  end
  resources :invoices, only: [:show] do
    resources :invoice_components
    resources :custom_invoice_components
  end

  get 'companies/:id/customers' => 'companies#customers', as: :company_customers
  get 'venues/:id/map_users' => 'venues#map_users', as: :map_users

  resources :memberships, only: [:create] do
    collection do
      post :import
      get :csv_template
    end
  end

  resources :venues do
    resources :game_passes
    resources :prices, except: [:index, :new, :edit] do
      member do
        post :merge_conflicts
      end
    end
    resources :courts do
    end
    resources :reservations do
      get 'new_cart', on: :collection
    end
    resources :memberships, except: [:new, :edit, :update]
    get 'memberships/:id/convert_to_cc' => 'memberships#convert_to_cc', as: :convert_to_cc
    post 'memberships/:id' => 'memberships#update'
    get 'offdays'
    resources :day_off, only: [:create, :destroy]
    get 'court_modal/:id' => 'venues#court_modal', as: :court_modal
    get 'price_modal/:id' => 'venues#price_modal', as: :price_modal
    get 'closing_hours'
    get 'booking_ahead_limit'
    get 'active_courts'
    post 'change_listed' => 'venues#change_listed', as: :change_listed
    member do
      get 'reports'
      post 'booking_sales_report'
      get 'available_court_indexes'
    end
    resources :discounts, except: [:new]
    get 'manage_discounts', as: :manage_discounts
    get 'edit_emails'
    post 'update_emails'
    resources :photos, only: [:create, :destroy] do
      post 'make_primary'
    end
    resources :email_lists do
      post 'remove_users'
      post 'add_users'
      get 'off_list_users'
    end
  end

  post '/custom_mail(.:format)' => 'email_lists#custom_mail'
  get 'reservations/:id/cancel' => 'reservations#refund', as: :reservation_refund
  get 'reservations/:id/cancel_reservation' => 'reservations#cancel', as: :reservation_cancel
  get 'reservations/:id/resell' => 'reservations#resell', as: :reservation_resell
  get 'reservations/:id/show_log' => 'reservations#show_log', as: :reservation_show_log
  get '/privacypolicy', :to => redirect('/privacypolicy.html')
  get '/termsofuse', :to => redirect('/termsofuse.html')
end

app/models/discount.rb
# Represents a discount that can be offered to customers.
class Discount < ActiveRecord::Base
  has_many :users, through: :discount_connections
  has_many :discount_connections, dependent: :destroy
  belongs_to :venue

  validates :method, presence: { message: 'Discount type cant be blank' }
  validates :name, presence: true
  validates :value,
            presence: true,
            numericality: { only_integer: true,
                            message: 'must be a number' }

  validate :correct_percentage

  enum method: [:percentage, :fixed]

  def correct_percentage
    if percentage? && !(0..100).cover?(value)
      errors.add('Percentage', 'must be between 0 and 100')
    end
  end

  def apply(original_price)
    price = if percentage?
              original_price * (1.0 - value / 100.0)
            else
              [original_price - value, 0].max
            end
    round ? price.round : price
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include CreditCards
  has_many :reservations, as: :user
  has_many :memberships
  has_many :venue_user_connectors, dependent: :destroy
  has_many :venues, through: :venue_user_connectors
  has_many :invoices
  has_many :discounts, through: :discount_connections
  has_many :discount_connections, dependent: :destroy
  has_many :email_list_user_connectors, dependent: :destroy
  has_many :email_lists, through: :email_list_user_connectors
  has_many :game_passes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable

  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, uniqueness: true

  # credit:
  # https://github.com/plataformatec/devise/wiki/How-To:-Find-a-user-when-you-have-their-credentials
  def self.authenticate(email, password)
    user = User.find_for_authentication(email: email)
    (user && user.valid_password?(password)) ? user : nil
  end

  def tz
    # TimeZone[self.timezone] || Time.zone
    Time.zone # TODO: change me to ActiveSupport::TimeZone with actual user timezone in the future
  end

  def outstanding_balance(company=nil)
    return 0.0 if !company.present?
    reservation_balance = company.reservations.where(user:self).where(is_billed: false).where(is_paid: false).sum(:price)
    game_pass_balance = company.game_passes.where(user:self).where(is_billed: false).where(is_paid: false).sum(:price)

    reservation_balance.to_f + game_pass_balance.to_f
  end

  def has_stripe?
    return self.stripe_id != nil
  end

  def has_game_pass?(venue)
    if self.game_passes.where(venue_id:venue.id).present?
      return true
    else
      return false
    end
  end

  def add_stripe_id(token)
    customer = Stripe::Customer.create(
      source: token,
      description: "Playven User"
    )
    self.update(stripe_id: customer.id)
  end

  def to_s
    "#{first_name} #{last_name}"
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def get_billing_address
    street_address.to_s + ' ' + zipcode.to_s + ' ' + city.to_s
  end

  # return discount or nil
  def discount_for(venue_id)
    @discounts_by_venue ||= discounts.group_by(&:venue_id)
    @discounts_by_venue[venue_id] ? @discounts_by_venue[venue_id].first : nil
  end

  def self.from_omniauth(auth)
    user_by_email = User.where(email: auth.info.email).first

    if user_by_email
      return user_by_email
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.first_name = auth.info.first_name
        user.last_name = auth.info.last_name
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.image = auth.info.image
        user.password = Devise.friendly_token[0,20]
      end
    end
  end

  def password_required?
    super if confirmed?
  end

  def password_match?
    errors[:password] << "can't be blank" if password.blank?
    errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def venue_discount(venue)
    discounts.find { |discount| discount.venue == venue }
  end

  def mixpanel_params
    {
      '$email'           => email,
      '$created'         => created_at,
      '$first_name'      => first_name,
      '$last_name'       => last_name,
      'id'               => id,
      'sign_in_count'    => sign_in_count,
      'last_sign_in'     => current_sign_in_at
    }
  end

  def future_reservations
    reservations.non_recurring.future
  end

  def past_reservations
    reservations.non_recurring.past
  end

  def future_memberships
    reservations.recurring.future
  end

  def past_memberships
    reservations.recurring.past
  end

  def reselling_memberships
    reservations.recurring.reselling
  end

  def resold_memberships
    Reservation.where(initial_membership_id: memberships.map(&:id))
  end

  def assign_discount(discount)
    old_discount = discounts.find_by(venue_id: discount.venue_id)
    discounts.delete(old_discount.id) if old_discount
    discounts << discount
  end

  def unconfirmed?
    !confirmed?
  end

  def self.find_or_create_by_id(user_params)
    if user_params[:user_id]
      User.find(user_params[:user_id])
    else
      User.find_or_create_by(email: user_params[:email]) do |user|
        user.assign_attributes(user_params.permit(:first_name, :last_name,
                                                  :email, :phone_number, :city,
                                                  :street_address, :zipcode))
        user.skip_confirmation_notification!
      end
    end
  end

  def self.search(query)
    query = "%#{query.to_s.strip}%"
    if query.present?
      full_name = Arel::Nodes::NamedFunction.new(
        'concat',
        [arel_table[:first_name],
        Arel::Nodes.build_quoted(' '),
        arel_table[:last_name]]
      )
      phone = Arel::Nodes::NamedFunction.new(
        "CAST",
        [arel_table[:phone_number].as("TEXT")]
      )
      where(full_name.matches(query)
              .or(arel_table[:email].matches(query))
              .or(phone.matches(query)))
    else
      all
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_company
  before_action :set_invoice, only: [:update, :show]

  def index
    @invoices = @company.invoices.includes(:user, :custom_invoice_components, invoice_components: { reservation: :court })
    @mode = params[:mode]
    case @mode
    when 'unpaid'
      @invoices = @invoices.unpaid
    when 'paid'
      @invoices = @invoices.paid
    else
      @mode = 'drafts'
      @invoices = @invoices.drafts
    end

    @outstanding_balances = @company.outstanding_balances
    users_with_balance = @outstanding_balances.map { |id,balance| id if balance != 0.0 }.compact
    @users = User.where(id: users_with_balance)
  end

  def create_drafts
    @users = User.where(id: invoice_drafts_params[:user_ids])
    redirect_to(:back, notice: "Please select some users") and return if @users.empty?
    @invoices = {} # user_id => invoice
    from = TimeSanitizer.input(TimeSanitizer.output(invoice_drafts_params[:start_date]).beginning_of_day.to_s)
    to = TimeSanitizer.input(TimeSanitizer.output(invoice_drafts_params[:end_date].to_date).end_of_day.to_s)
    @users.each do |user|
      reservations = user.reservations.
        where('? <= start_time and end_time <= ?',
              from, to).
        where(is_billed: false).
        where(court_id: @company.court_ids)
      if reservations.any?
        @invoices[user.id] = Invoice.create_for_company_and_reservations(@company, reservations, user)
        #price number_with_precision(@invoice.invoice_components.map(&:price).inject(:+), :precision => 2)
      end
    end
    if @invoices.keys.empty?
      redirect_to :back, notice: "There's nothing to invoice for this period."
    else
      redirect_to company_invoices_path(@company), notice: "#{@invoices.keys.size} invoices were generated successfully. Now review and send them."
    end
  end

  def send_all
    params[:selected_ids].each do |id|
      @company.invoices.find(id).send!
    end
    redirect_to company_invoices_path(@company),
      notice: "#{params[:selected_ids].size} invoices were sent out successfully"
  end

  def mark_paid
    count = Invoice.mark_paid(params[:selected_ids])
    redirect_to company_invoices_path(@company),
      notice:  t('.success', count: count)
  end

  def destroy_all
    params[:selected_ids].each do |id|
      @company.invoices.find(id).destroy
    end
    redirect_to company_invoices_path(@company, mode: 'unpaid'),
      notice: "#{params[:selected_ids].size} invoices were deleted successfully"
  end

  def update
    @invoice.assign_attributes(invoice_params)
    if @invoice.save
      render json: {status: 'updated', invoice: { total: @invoice.total }}
    else
      render json: {error: 'validation error'}
    end
  end

  def show
    @invoice = Invoice.includes(:user, invoice_components: { reservation: :court }).find(params[:id])
    @customer = @invoice.user
  end

  def create_report
    from = TimeSanitizer.input(TimeSanitizer.output(report_params[:from]).beginning_of_day.to_s)
    to = TimeSanitizer.input(TimeSanitizer.output(report_params[:to]).end_of_day.to_s)
    invoices = @company.invoices.includes(:user).where(billing_time: from..to, is_draft: false).order(:created_at)
    report = Invoice.generate_invoice_excel(@company, invoices, current_admin, from, to)
    range = [from, to].map{|t| t.strftime('%d-%m-%Y')}.join('_')
    filename = "Invoice_Report_#{range}.xlsx"
    send_data report.to_stream.read, filename: filename
  end

  protected

  def set_company
    if current_admin.try(:company)
      @company = current_admin.company
    elsif Company.find(params[:company_id])
      @company = Company.find(params[:company_id])
    end
  end

  def set_invoice
    @invoice = @company.invoices.find(params[:id])
  end

  def invoice_params
    params.require('invoice').permit(:total)
  end

  def invoice_drafts_params
    params.permit(:start_date, :end_date, :user_ids => [])
  end

  def report_params
    params.require(:report).permit(:from, :to)
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_create_invoices.html.erb
<div class="panel-body">
  <div class="ibox float-e-margins">
    <div class="">
        <h3><%= t('.header')%></h3>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <%= form_tag create_drafts_company_invoices_path(@company) do %>
                    <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="8" data-filter=#filter>
                        <thead>
                        <tr>
                            <th data-toggle="true"><%= t('.table_head_name')%></th>
                            <th><%= t('.table_head_email')%></th>
                            <th><%= t('.table_head_id')%></th>
                            <th><%= t('.table_head_balance')%></th>
                            <th><%= t('.table_head_action')%></th>
                        </tr>
                        </thead>
                        <tbody>
                        <% @users.each do |user| %>
                          <tr>
                              <td><%= user.full_name %></td>
                              <td><%= user.email %></td>
                              <td><%= user.id %></td>
                              <td><%= number_to_currency(@outstanding_balances[user.id].to_f) %></td>
                              <td><%= check_box_tag 'user_ids[]', user.id%></td>
                          </tr>
                        <% end %>
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="5">
                                <ul class="pagination pull-right"></ul>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                    <div class="col-md-2">
                      <div class="input-group date" data-provide="datepicker">
                        <input type="text" name="start_date" class="form-control datepicker" data-date-format="dd/mm/yyyy" value="<%= (Date.today - 30.days).strftime("%d/%m/%Y") %>" required>
                        <div class="input-group-addon">
                          <span class="fa fa-calendar"></span>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-2">
                      <div class="input-group date" data-provide="datepicker">
                        <input type="text" name="end_date" class="form-control datepicker" data-date-format="dd/mm/yyyy" value="<%= Date.today.strftime("%d/%m/%Y") %>" required>
                        <div class="input-group-addon">
                          <span class="fa fa-calendar"></span>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-2">
                        <%= submit_tag t('.submit_button'), class: "form-control btn-default" %>
                    </div>

                    <% end %>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>

app/views/invoices/_custom_invoice_component_form.html.erb
<%= form_for :custom_invoice_component, url: '', method: :post, remote: true, html: { 'data-type': 'json' } do |f| %>
  <div class='row'>
    <div class='col-sm-6'>
      <div className="form-group">
        <%= t('.name') %>
      </div>
    </div>
    <div class='col-sm-3'>
      <div className="form-group">
        <%= t('.price') %>
      </div>
    </div>
    <div class='col-sm-3'>
      <div className="form-group">
        <%= t('.vat') %>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-6'>
      <div className="form-group">
        <%= f.text_field :name, class: 'form-control', required: true %>
      </div>
    </div>
    <div class='col-sm-3'>
      <div className="form-group">
        <%= f.text_field :price, class: 'form-control', required: true, data: { 'rule-number': true } %>
      </div>
    </div>
    <div class='col-sm-3'>
      <div className="form-group">
        <%= f.select :vat_decimal, CustomInvoiceComponent::DEFAULT_VAT_DECIMALS.map { |vat| [ "#{vat*100}%", vat] }, { prompt: t('.select') }, class: 'form-control', required: true %>
      </div>
    </div>
  </div>
  <div class='row'>
    <br/>
    <div class='col-sm-12 text-right'>
      <div class='cancel-btn-JS btn btn-default btn-sm'><%= t('.cancel') %></div>

      <%= button_tag type: 'submit', class: "submit-btn-JS btn btn-primary btn-sm" do %>
        <%= t('.create') %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/invoices/_drafts_table.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
            <input type="text" class="form-control input-sm m-b-xs" id="filter"
                    placeholder="<%= t('.search_placeholder')%>">

                <table class="footable table table-stripped toggle-arrow-tiny js-draft-invoices-table" data-page-size="8" data-filter=#filter>
                    <thead>
                    <tr>
                      <th data-toggle="true"><%= t('.table_head_name')%></th>
                      <th><%= t('.table_head_email')%></th>
                      <th><%= t('.table_head_total')%></th>
                      <th data-hide="all"></th>
                      <th><%= t('.table_head_pdf')%></th>
                      <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @invoices.each do |invoice| %>
                      <% user = invoice.user %>
                        <tr data-id="<%= invoice.id%>">
                          <td><%= user.try(:full_name) %></td>
                          <td><%= user.try(:email) %></td>
                          <td><%= number_to_currency(invoice.total) %></td>
                          <td class='hidden'>
                            <table class="table">
                              <tr>
                                <th><%= t('.invoice.table_head_date') %></th>
                                <th><%= t('.invoice.table_head_start_time') %></th>
                                <th><%= t('.invoice.table_head_end_time') %></th>
                                <th><%= t('.invoice.table_head_court') %></th>
                                <th><%= t('.invoice.table_head_price') %></th>
                                <th><%= t('.invoice.table_head_action') %></th>
                              </tr>
                              <% invoice.invoice_components.sort_by(&:start_time).each do |ic| %>
                                <tr id="invoice_component_<%=ic.id%>">
                                  <td><%= ic.start_time.try(:strftime, '%d %B %Y') %></td>
                                  <td><%= TimeSanitizer.output(ic.start_time).try(:strftime, '%H:%M') %></td>
                                  <td><%= TimeSanitizer.output(ic.end_time).try(:strftime, '%H:%M') %></td>
                                  <td><%= ic.court_name %></td>
                                  <td><%= number_to_currency(ic.price) %></td>
                                  <td><%= link_to t('.delete_link'), invoice_invoice_component_path(invoice, ic),
                                    data: {remote: true, method: :delete, confirm: t('.delete_confirm') }
                                  %></td>
                                </tr>
                              <% end %>
                              <% if invoice.custom_invoice_components.any? %>
                                <tr>
                                  <th colspan="3"><%= t('.invoice.table_head_custom_name') %></th>
                                  <th><%= t('.invoice.table_head_vat') %></th>
                                  <th><%= t('.invoice.table_head_price') %></th>
                                  <th><%= t('.invoice.table_head_action') %></th>
                                </tr>
                              <% end %>
                              <% invoice.custom_invoice_components.sort_by(&:created_at).each do |cic| %>
                                <tr id="custom_invoice_component_<%=cic.id%>">
                                  <td colspan="3"><%= cic.name %></td>
                                  <td><%= cic.vat_to_s %></td>
                                  <td><%= number_to_currency(cic.price) %></td>
                                  <td><%= link_to t('.delete_link'), invoice_custom_invoice_component_path(invoice, cic),
                                    data: {remote: true, method: :delete, confirm: t('.delete_confirm') }
                                  %></td>
                                </tr>
                              <% end %>
                              <tr>
                                <td colspan="6">
                                  <div id='add-custom-invoice-component' class='btn btn-default btn-sm' data-url='<%= invoice_custom_invoice_components_path(invoice)%>'>
                                    <%= t('.add_custom') %>
                                  </div>
                                </td>
                              </tr>
                              <tr>
                                <td colspan="3"></td>
                                <td><strong><%= t(".total")%></strong></td>
                                <td colspan="2">
                                  <strong id="invoice_<%= invoice.id %>_total"><%= invoice.total %></strong>
                                  <input type="hidden"/><!--needed for footable to not create duplicated rows-->
                                </td>
                              </tr>
                            </table>
                          </td>
                          <td><%= link_to t('.pdf_link'), company_invoice_path(@company, invoice, format: :pdf) %></td>
                          <td><input type="checkbox" name="invoice_ids" value="<%= invoice.id %>"></td>
                        </tr>
                    <% end %>

                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="3">
                            <ul class="pagination"></ul>
                        </td>
                        <td colspan="3">
                          <div class="pull-right">
                            <%= link_to t('.delete_selected_link'), destroy_all_company_invoices_path(@company),
                              class: 'disabled js-invoices-multiple-action btn btn-danger',
                              data: {
                                confirm: t('.delete_selected_confirm'),
                                method: :post,
                                url: destroy_all_company_invoices_path(@company)
                              }
                            %>
                            <%= link_to t('.send_link'), send_all_company_invoices_path(@company),
                              class: 'disabled js-invoices-multiple-action btn btn-success',
                              data: {
                                confirm: t('.send_confirm'),
                                method: :post,
                                url: send_all_company_invoices_path(@company)
                              }
                            %>
                          </div>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

<div id='custom-invoice-component-form-container' class='hidden'>
  <%= render 'custom_invoice_component_form' %>
</div>

<script type="text/javascript">

$(document).ready(function() {
    $('.footable').footable();

    // multiple invoices action logic
    var $multipleButtons = $('.js-invoices-multiple-action');
    $('input[name=invoice_ids]').on('change', function() {
      var $selected = $('input[name=invoice_ids]:checked');
      var selectedIds = $selected.map(function() {
        return $(this).val();
      }).toArray();
      if (selectedIds.length === 0) {
        $multipleButtons.addClass('disabled');
        $multipleButtons.each(function() {
          $(this).attr('href', '#');
        });
      } else {
        $multipleButtons.removeClass('disabled');
        $multipleButtons.each(function() {
          var url = $(this).data('url') + '?' + selectedIds.map(function(id) {
            return 'selected_ids[]=' + id;
          }).join('&');
          $(this).attr('href', url);
        });
      }
    });
});
</script>

app/views/invoices/_invoice_table.html.erb
<table class="footable">
  <tr>
    <th><%= t('.table_head_start_time')%></th>
    <th><%= t('.table_head_end_time')%></th>
    <th><%= t('.table_head_court')%></th>
    <th><%= t('.table_head_price')%></th>
  </tr>
  <% total = 0.0 %>
  <% invoice.invoice_components.each do |ic| %>
    <% total += ic.price %>
    <tr>
      <td><%= ic.start_time %></td>
      <td><%= ic.end_time %></td>
      <td><%= ic.court_name %></td>
      <td><%= ic.price %></td>
    </tr>
  <% end %>
  <tr>
    <td colspan="2"></td>
    <td><strong><%= t('.total')%></strong></td>
    <td><strong><%= total %></strong></td>
  </tr>
</table>

app/views/invoices/index.html.erb
<div class="wrapper wrapper-content  animated fadeInRight">
   <div class="row m-t-lg">
       <div class="col-lg-12">
           <div class="tabs-container">
               <ul class="nav nav-tabs">
                   <li class="active"><a data-toggle="tab" href="#tab-1"><%= t('.invoices')%></a></li>
                   <% if can? :manage, Invoice %>
                     <li class=""><a data-toggle="tab" href="#tab-2"><%= t('.create_invoices')%></a></li>
                   <% end %>
               </ul>
               <div class="tab-content">
                   <div id="tab-1" class="tab-pane active">
                    <%= render 'invoice_list' %>
                   </div>
                   <% if can? :manage, Invoice %>
                     <div id="tab-2" class="tab-pane">
                       <%= render 'create_invoices' %>
                     </div>
                   <% end %>
               </div>


           </div>
       </div>
   </div>
</div>


<script type="text/javascript">

$(document).ready(function() {

    $('.footable').footable();
    $('.footable2').footable();


});

</script>