config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get 'venues/:id/view' => 'venues#view', as: :venue_view
  post 'venues/:id/available' => 'venues#available', as: :venue_available
  get 'venues/:id/make_reservation' => 'venues#make_reservation',
      as: :venue_make_reservationget
  post 'venues/:id/make_reservation' => 'venues#make_reservation',
       as: :venue_make_reservation

  get 'venues/:id/make_unpaid_reservation' => 'venues#make_unpaid_reservation',
      as: :venue_make_unpaid_reservationget
  post 'venues/:id/make_unpaid_reservation' => 'venues#make_unpaid_reservation',
       as: :venue_make_unpaid_reservation

  get 'venues/:id/court_price_at' => 'venues#court_price_at',
      as: :court_price_at
  get 'venues/:id/manage_venue' => 'venues#courts_and_prices',
      as: :courts_and_prices

  post '/search' => 'pages#search', as: :search
  get '/search' => 'pages#search', as: :searchget

  get "search_venues" => "search#show", as: :search_venues
  get 'venues/:id/cancelled_reservations' => 'venues#cancelled_reservations', as: :venue_cancelled_reservations



  get 'venues/:id/memberships' => 'venues#memberships', as: :memberships

  get 'users/:id/invoices' => 'users#invoices', as: :user_invoices

  root 'pages#home'

  get '/search' => 'pages#search'
  post '/search' => 'pages#search'

  namespace :api do
    post 'authenticate' => 'auth#authenticate'
    get '/auth/facebook' => 'auth#facebooklogin'
    get "sort_by_sport" => "venues#sort_by_sport"
    resources :users, only: [:create, :update] do
      get 'game_pass_check'

      collection do
        post :confirm_account
        post :reset_password
      end
    end
    resources :companies, only: [] do
      post 'send_support_email'
    end
    get 'search' => 'venues#search'
    get 'all_sport_names' => 'venues#all_sport_names'
    resources :cards, only: [:create, :index]
    resources :reservations, only: [:create, :index, :destroy]
    resources :subscriptions, only: [:index]
    resources :venues, only: [:show, :index] do
      get 'users'
      get 'utilization_rate'
      get 'available_courts'
    end
    resources :game_passes, only: [:index, :show, :create, :update, :destroy] do
      collection do
        get :court_sports
        get :court_types
        get :templates
        get :available
      end
    end
  end

  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'

  devise_for :admins,
             controllers: { confirmations: 'confirmations' }

  devise_for  :users,
              path: '',
              path_names: { sign_in: 'login',
                            sign_out: 'logout',
                            edit: 'profile' },
              controllers: { omniauth_callbacks: 'omniauth_callbacks',
                             registrations: 'registrations',
                             confirmations: 'confirmations' }

  devise_scope :user do
    patch '/users/confirm' => 'confirmations#confirm',
          as: :user_confirm
    patch 'users/update_password' => 'registrations#update_password'
  end

  devise_scope :admin do
    patch '/admins/confirm' => 'confirmations#confirm',
          as: :admin_confirm
    authenticate :admin, lambda { |admin| admin.god? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  resources :users, only: [:show] do
    post 'add_card' => 'stripe#add_card', as: :add_card
    post 'card_reminder'
    post 'assign_discount', as: :assign_discount
    get  'recurring_reservations', on: :member
  end

  resources :companies do
    resources :admins, expect: [:new, :show]
    get :reports
    post :create_report
    get :report
    resources :invoices do
      collection do
        post :create_drafts
        post :send_all
        post :mark_paid
        post :destroy_all
        post :create_report
      end
    end
    get 'revenue' => 'dashboard#revenue', as: :revenue
    get 'resv' => 'dashboard#resv'
    member do
      post 'import_customers'
      get  'customers_csv_template'
    end
  end
  resources :invoices, only: [:show] do
    resources :invoice_components
    resources :custom_invoice_components
  end

  get 'companies/:id/customers' => 'companies#customers', as: :company_customers
  get 'venues/:id/map_users' => 'venues#map_users', as: :map_users

  resources :memberships, only: [:create] do
    collection do
      post :import
      get :csv_template
    end
  end

  resources :venues do
    resources :game_passes
    resources :prices, except: [:index, :new, :edit] do
      member do
        post :merge_conflicts
      end
    end
    resources :courts do
    end
    resources :reservations do
      get 'new_cart', on: :collection
    end
    resources :memberships, except: [:new, :edit, :update]
    get 'memberships/:id/convert_to_cc' => 'memberships#convert_to_cc', as: :convert_to_cc
    post 'memberships/:id' => 'memberships#update'
    get 'offdays'
    resources :day_off, only: [:create, :destroy]
    get 'court_modal/:id' => 'venues#court_modal', as: :court_modal
    get 'price_modal/:id' => 'venues#price_modal', as: :price_modal
    get 'closing_hours'
    get 'booking_ahead_limit'
    get 'active_courts'
    post 'change_listed' => 'venues#change_listed', as: :change_listed
    member do
      get 'reports'
      post 'booking_sales_report'
      get 'available_court_indexes'
    end
    resources :discounts, except: [:new]
    get 'manage_discounts', as: :manage_discounts
    get 'edit_emails'
    post 'update_emails'
    resources :photos, only: [:create, :destroy] do
      post 'make_primary'
    end
    resources :email_lists do
      post 'remove_users'
      post 'add_users'
      get 'off_list_users'
    end
  end

  post '/custom_mail(.:format)' => 'email_lists#custom_mail'
  get 'reservations/:id/cancel' => 'reservations#refund', as: :reservation_refund
  get 'reservations/:id/cancel_reservation' => 'reservations#cancel', as: :reservation_cancel
  get 'reservations/:id/resell' => 'reservations#resell', as: :reservation_resell
  get 'reservations/:id/show_log' => 'reservations#show_log', as: :reservation_show_log
  get '/privacypolicy', :to => redirect('/privacypolicy.html')
  get '/termsofuse', :to => redirect('/termsofuse.html')
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :admins, dependent: :destroy
  has_many :venues, dependent: :destroy
  has_many :users, through: :venues
  has_many :reservations, through: :venues
  has_many :game_passes, through: :venues
  has_many :courts, through: :venues
  has_many :invoices, dependent: :destroy
  serialize :stripe_account_status, JSON

  # Stripe::BalanceTransaction.all({:transfer => "tr_17yKSgBavI8QpPIoLEJe4Zut"}, {:stripe_account => self.stripe_user_id})

  def user_reservations(user)
    reservations.where(user: user).order(start_time: :asc)
  end

  def connected?; !stripe_user_id.nil?; end

  def managed?; stripe_account_type == 'managed'; end

  def manager
    case stripe_account_type
    when 'managed' then StripeManaged.new(self)
    end
  end

  def can_accept_charges
    return true if managed? && stripe_account_status['charges_enabled']
    return false
  end

  def transfers(start_date, end_date)
    Stripe::Transfer.all({:date => {gte:(DateTime.parse(start_date)).to_i, lte:(DateTime.parse(end_date)).to_i}},{stripe_account: self.stripe_user_id})
  end

  def transfer_transactions(transfer)
    Stripe::BalanceTransaction.all({:transfer => transfer}, {:stripe_account => self.stripe_user_id})
  end

  def trans_hist(grouping)
    Stripe::BalanceTransaction.all(self.filter(grouping), {stripe_account: self.stripe_user_id})
  end

  def balance
    Stripe::Balance.retrieve({stripe_account: self.stripe_user_id}).pending[0].amount / 100
  end

  def charges_data(grouping)
    data = self.charges(grouping)
    amount = 0
    data.each do |d|
      amount += d.amount
    end

    {
      count: data.count,
      amount: amount/100
    }
  end

  def charges(grouping)
    Stripe::Charge.all(self.filter(grouping),
    {stripe_account: self.stripe_user_id}).data
  end

  def customers
    customers = []
    User.all.each do |user|
      companies = user.reservations.map do |resv|
        resv.court.venue.company
      end
      customers << user unless not companies.include? self
    end
    return customers
  end

  def user_outstanding_balance(user)
    invoicable_reservations = reservations.where(user: user).invoicable
    invoicable_game_passes = game_passes.where(user: user).invoicable

    invoicable_reservations.map(&:outstanding_balance).sum.to_f +
      invoicable_game_passes.map(&:price).sum.to_f
  end

  def outstanding_balances
    invoicable_reservations = reservations.invoicable.group_by(&:user_id)
    invoicable_game_passes = game_passes.invoicable.group_by(&:user_id)

    user_ids = invoicable_reservations.keys + invoicable_game_passes.keys

    user_ids.map do |user_id|
      [user_id,
        invoicable_reservations[user_id].try(:map, &:outstanding_balance).try(:sum).to_f +
        invoicable_game_passes[user_id].try(:map, &:price).try(:sum).to_f
      ]
    end.to_h
  end

  def filter(grouping)
    case
    when grouping == 'day'
      {
        created: {
          gte: Time.now.beginning_of_day.to_i,
          lt: Date.tomorrow.beginning_of_day.to_i
        }
      }
    when grouping == 'month'
      {
        created: {
          gte: Time.now.beginning_of_month.to_i,
          lt: Time.now.beginning_of_month.next_month.to_i
        }
      }
    when grouping == 'year'
      {
        created: {
          gte: Time.now.beginning_of_year.to_i,
          lt: Time.now.beginning_of_year.next_year.to_i
        }
      }
    end
  end

  def has_stripe?
    stripe_user_id != nil
  end

  def last_god?(admin)
    !admins.any? { |a| a != admin && a.role?('god') }
  end

  # return VAT decimal based on company_business_type
  # decimal = percentage / 100
  # TODO use enum for company_business_type
  def get_vat_decimal
    case company_business_type
    when 'Rekisteröity yhdistys'
      BigDecimal.new('0')
    else
      BigDecimal.new('0.10')   # 10 %
    end
  end
end

app/controllers/api/companies_controller.rb
class API::CompaniesController < ApplicationController

  def send_support_email
    SupportMailer.support_email(params[:title], params[:content], current_admin.email, current_admin.company.company_legal_name).deliver!
    render nothing: true, status: :ok
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, except: [:new, :create]
  before_action :authenticate_admin!

  authorize_resource

  def index
  end

  def show
    @resv_data = @company.charges_data('month') if @company.has_stripe?
    @venues = @company.venues
  end

  def customers
    @users =  User.search(params[:search])
                  .where(id: @company.users)
                  .order(:created_at)
                  .page(params[:page]).per_page(10)
    @outstanding_balances = @company.outstanding_balances
    @reservations = @company.reservations.where(user: @users).group_by(&:user_id)
  end

  def invoices
  end

  def new
    @company = current_admin.build_company
    render layout: 'newlayout'
  end

  def reports
  end

  def create_report
    @transfers = current_company.transfers(params['report']['start_date'],
                                           params['report']['end_date'])
    render :report
  end

  def report
    @transfers = current_company.transfers(params['start'], params['end'])
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      current_company = @company
      current_admin.update_attribute :company_id, @company.id
      connector = StripeManaged.new(current_company)
      account = connector.create_account!(current_company,
                                          current_admin,
                                          params[:tos] == 'on',
                                          request.remote_ip)
      if account
        flash[:notice] = "Managed Stripe account created! \
                          <a target='_blank' rel='platform-account' \
                          href='https://dashboard.stripe.com/test/
                          applications/users/#{account.id}'>View \
                          in dashboard &raquo;</a>"
      else
        flash[:error] = 'Unable to create Stripe account!'
      end
      redirect_to @company, notice: 'Saved...'
    else
      render :new, layout: 'empty'
    end
  end

  def edit
    @venues = @company.venues
  end

  def update
    if @company.update(company_params)
      redirect_to @company, notice: 'Updated...'
    else
      render :edit
    end
  end

  # post
  def import_customers
    @venue = Venue.find(params[:venue_id])

    importer = CSVImportUsers.new(params[:csv_file], @venue)
    @report = importer.run.report_message
    @failed_customers = importer.invalid_rows

    respond_to do |format|
      format.js
      format.html { redirect_to :back, notice: @report }
    end
  end

  def customers_csv_template
    send_data CSVImportUsers.csv_template, filename: "customers_csv_template.csv"
  end

  private

  def set_company
    @company = current_admin.company
  end

  def company_params
    params.require(:company)
          .permit(:company_legal_name, :company_country,
                  :company_business_type, :company_tax_id,
                  :company_street_address, :company_zip,
                  :company_city, :company_website,
                  :company_iban, :company_phone,
                  :active)
  end

  def current_company
    @company
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_customers_table.html.erb
<table class="footable table table-stripped toggle-arrow-tiny">
  <thead>
    <tr>
      <th data-toggle="true" data-sort-ignore="true"><%= t('.table_header_name')%></th>
      <th data-sort-ignore="true"><%= t('.table_header_email')%></th>
      <th data-sort-ignore="true"><%= t('.table_header_id')%></th>
      <th data-sort-ignore="true"><%= t('.table_header_balance')%></th>
      <th data-hide="all" data-sort-ignore="true"><%= t('.table_header_phone_number')%></th>
      <th data-hide="all" data-sort-ignore="true"><%= t('.table_header_reservation_done')%></th>
      <th data-hide="all" data-sort-ignore="true"><%= t('.table_header_last_reservation')%></th>
      <th data-hide="all" data-sort-ignore="true"><%= t('.table_header_lifetime')%></th>
      <th data-sort-ignore="true"><%= t('.table_header_action')%></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td><%= user.id %></td>
        <td><%= @outstanding_balances[user.id].to_f %></td>
        <td><%= user.try(:phone_number) %></td>
        <% if @reservations[user.id] %>
          <td><%= @reservations[user.id].count %></td>
          <td><%= @reservations[user.id].last.start_time.strftime('%d/%m/%Y') %></td>
          <td><%= number_to_currency(@reservations[user.id].map(&:price).sum.to_f) %></td>
        <% else %>
          <td>0</td>
          <td>--</td>
          <td><%= number_to_currency(0.0) %></td>
        <% end %>
        <td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="5">
        <ul class="pull-right"><%= will_paginate @users %></ul>
      </td>
    </tr>
  </tfoot>
</table>

<script type="text/javascript">
  $('.footable').footable({ paginate: false });

  $('#customers-table-cantainer .pagination > a').on('click', function(e) {
    e.preventDefault();
    $('#customers-table-cantainer .pagination > a').addClass('disabled');
    ajax_turboclick_link($(this).attr('href'));
  });
</script>

app/views/companies/_transfer_details.html.erb
<table class="footable table table-stripped toggle-arrow-tiny">
    <thead>
    <tr>
        <th><%= t('.table_head_amount') %></th>
        <th><%= t('.table_head_fee') %></th>
        <th><%= t('.table_head_net') %></th>
        <th><%= t('.table_head_date') %></th>
        <th><%= t('.table_head_type') %></th>
    </tr>
    </thead>
    <tbody>
          <% transfers.each do |transfer| %>
          <tr>
            <td><%= number_to_currency(transfer.amount/100.0) %></td>
            <td><%= number_to_currency(transfer.fee/100.0) %></td>
            <td><%= number_to_currency(transfer.net/100.0) %></td>
            <td><%= Time.at(transfer.created).to_datetime.strftime("%d/%m/%Y") %></td>
            <td><%= transfer.type %></td>
          </tr>
          <% end %>
    </tbody>
</table>

app/views/companies/create.html.erb
<h1>Companies#create</h1>
<p>Find me in app/views/companies/create.html.erb</p>

app/views/companies/customers.html.erb
<div class="wrapper wrapper-content animated fadeInRight">

<div class="row">
    <div class="col-lg-12">
      <div class="tabs-container">
        <ul class="nav nav-tabs">
          <li class="active"><a data-toggle="tab" href="#tab-1"><%= t('.header') %></a></li>
          <li><a data-toggle="tab" href="#tab-2"><%= t('.import') %></a></li>
        </ul>
        <div class="tab-content">
          <div id="tab-1" class="tab-pane active">
            <div class="panel-body">
              <div class="row">
                <div class="col-lg-12">
                  <div class="ibox float-e-margins">
                    <div class="ibox-content">
                      <input type="text" class="form-control input-sm m-b-xs" id="filter"
                           placeholder="<%= t('.search_placeholder') %>"
                           value='<%= sanitize params[:search] %>'>

                      <div id='customers-table-cantainer'>
                        <%= render 'customers_table' %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div id="tab-2" class="tab-pane">
            <div class="panel-body">
              <div class="row">
                <div class="col-lg-12">
                  <div class="ibox float-e-margins">
                    <div class="ibox-content">
                      <%= form_tag import_customers_company_path(@company), remote: true do %>
                        <div class="row">
                          <div class="col-md-4">
                            <div class="form-group">
                              <%= label_tag :csv_file, t('.venue'), class: 'control-label' %>
                              <%= select '', :venue_id, @company.venues.map {|v| [ v.venue_name, v.id ] }, include_blank: false, class: 'form-control' %>
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-md-4">
                            <div class="form-group">
                              <%= label_tag :csv_file, t('.csv_file'), class: 'control-label' %>
                              <input type="file" class="form-control" name="csv_file" class="file">
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-md-4">
                            <br>
                            <%= button_tag type: 'submit', class:"btn", data: { disable_with: t('.importing') } do %>
                              <%= t('.upload_button') %>
                            <% end %>
                          </div>
                        </div>
                      <% end %>

                      <hr/>
                      <div class="row">
                        <div class="col-lg-12" id='csv-import-report'>
                        </div>
                      </div>

                      <hr/>
                      <%= link_to t('.download_csv_template'), customers_csv_template_company_path(@company) %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
</div>

<script type="text/javascript">
  $('#filter').on('keyup', function(e) {
    if (e.keyCode == 13) {
      ajax_turboclick_link('<%= company_customers_path(@company) %>' + '?search=' + $(this).val());
    }
  });
</script>

app/views/companies/customers.js.erb
$('#customers-table-cantainer').html("<%= j render('customers_table') %>");

app/views/companies/import_customers.js.erb
$('#csv-import-report').html("<div><b><%= j @report %></b></div>");

<% if @failed_customers.any? %>
  $('#csv-import-report').append("<div><%= j I18n.t('companies.customers_import.failures') %>:</div>");
  <% @failed_customers.each do |c| %>
    $('#csv-import-report').append("<div><b><%= j sanitize(c.email.present? ? c.email : '---') %></b>: <%= j sanitize(c.errors.full_messages.join('; ')) %></div>");
  <% end %>
<% end %>

app/views/companies/index.html.erb
<h1>Companies#index</h1>
<p>Find me in app/views/companies/index.html.erb</p>

app/views/companies/report.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2> <%= t('.title') %> </h2>
        <ol class="breadcrumb">
            <li>
                <a href="index.html"><%= t('.header', name: @company.company_legal_name) %></a>
            </li>
            <li class="active">
                <strong><%= t('.title') %></strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
      <div class="col-lg-12">
          <div class="ibox float-e-margins">
              <div class="ibox-title">
                  <h5><%= t('.transfers_title') %></h5>

                  <div class="ibox-tools">
                      <a class="collapse-link">
                          <i class="fa fa-chevron-up"></i>
                      </a>
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                          <i class="fa fa-wrench"></i>
                      </a>
                      <ul class="dropdown-menu dropdown-user">
                          <li><a href="#">Config option 1</a>
                          </li>
                          <li><a href="#">Config option 2</a>
                          </li>
                      </ul>
                      <a class="close-link">
                          <i class="fa fa-times"></i>
                      </a>
                  </div>
              </div>
              <div class="row">
                  <div class="col-lg-12">
                      <div class="ibox float-e-margins">
                          <div class="ibox-content">
                            <h2> <%= link_to t('.pdf_link'), company_report_path(@company, format: :pdf, start: params[:report][:start_date], end: params[:report][:end_date]) %></h2>

                              <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="8" data-filter=#filter>
                                  <thead>
                                  <tr>

                                      <th data-toggle="true"><%= t('.table_header_amount')%></th>
                                      <th><%= t('.table_header_date')%></th>
                                      <th data-hide="all"></th>
                                  </tr>
                                  </thead>
                                  <tbody>
                                        <% @transfers["data"].each do |t| %>
                                        <tr>
                                          <td><%= number_to_currency(t.amount/100.0) %></td>
                                          <td>
                                            <%= Time.at(t.date).to_datetime.strftime("%d/%m/%Y") %>
                                          </td>
                                          <td>
                                            <%= render partial: "companies/transfer_details", locals: { transfers: @company.transfer_transactions(t.id) } %>
                                          </td>
                                        </tr>
                                        <% end %>
                                  </tbody>
                                  <tfoot>
                                  <tr>
                                      <td colspan="5">
                                          <ul class="pagination pull-right"></ul>
                                      </td>
                                  </tr>
                                  </tfoot>
                              </table>

                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
    $('.footable').footable();
});
</script>

app/views/companies/reports.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2> <%= t('.title') %> </h2>
        <ol class="breadcrumb">
            <li>
                <a href="index.html"><%= t('.header', name: @company.company_legal_name) %></a>
            </li>
            <li class="active">
                <strong><%= t('.title') %></strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="tabs-container">
        <ul class="nav nav-tabs">
          <li class="active"><a data-toggle="tab" href="#tab-1"><%= t('.transfers_title') %></a></li>
          <li><a data-toggle="tab" href="#tab-2"><%= t('.invoices_report') %></a></li>
        </ul>
        <div class="tab-content">
          <div id="tab-1" class="tab-pane active">
            <div class="panel-body">
              <div class="row">
                <div class="col-lg-12">
                  <div class="ibox float-e-margins">
                    <div class="ibox-content">
                      <h2><%= t('.download_title') %></h2>
                      <%= form_tag company_create_report_path(@company) do %>
                        <div class="row">
                        <div class="col-md-4">
                          <h3><%= t('.from') %>:</h3>
                            <div class="input-group date" data-provide="datepicker">
                              <input type="text" class="form-control" id="searchDate" name="report[start_date]" class="datepicker" data-date-format="dd/mm/yyyy" value="<%= Time.now.strftime("%d/%m/%Y") %>">
                              <div class="input-group-addon">
                                <span class="fa fa-calendar"></span>
                              </div>
                            </div>
                          </div>
                          <div class="col-md-4">
                            <h3><%= t('.to') %>:</h3>
                            <div class="input-group date" data-provide="datepicker">
                              <input type="text" class="form-control" id="searchDate" name="report[end_date]" class="datepicker" data-date-format="dd/mm/yyyy" value="<%= Time.now.strftime("%d/%m/%Y") %>">
                              <div class="input-group-addon">
                                <span class="fa fa-calendar"></span>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-md-4">
                            <br>
                            <%= submit_tag t('.download_button'), class:"btn" %>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div id="tab-2" class="tab-pane">
            <div class="panel-body">
              <div class="row">
                <div class="col-lg-12">
                  <div class="ibox float-e-margins">
                    <div class="ibox-content">
                      <%= form_tag create_report_company_invoices_path(@company) do %>
                        <div class="row">
                          <div class="col-md-4">
                          <h3><%= t('.from') %>:</h3>
                            <div class="input-group date" data-provide="datepicker">
                              <input type="text" class="form-control" name="report[from]" class="datepicker" data-date-format="dd/mm/yyyy" value="<%= Time.now.strftime("%d/%m/%Y") %>">
                              <div class="input-group-addon">
                                <span class="fa fa-calendar"></span>
                              </div>
                            </div>
                          </div>
                          <div class="col-md-4">
                          <h3><%= t('.to') %>:</h3>
                            <div class="input-group date" data-provide="datepicker">
                              <input type="text" class="form-control" name="report[to]" class="datepicker" data-date-format="dd/mm/yyyy" value="<%= Time.now.strftime("%d/%m/%Y") %>">
                              <div class="input-group-addon">
                                <span class="fa fa-calendar"></span>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-md-4">
                            <br>
                            <%= button_tag type: 'submit', class:"btn" do %>
                              <i class='fa fa-file-excel-o m-r-xs'></i> <%= t('.download_button') %>
                            <% end %>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
    $('.footable').footable();
});
</script>

app/views/companies/show.html.erb
<input type="hidden" value="<%= @company.id %>" id="company-info">

<% if !@company.managed? %>
<div class="row">
    <%= form_tag stripe_managed_path, method: 'POST' do %>
        Stripe Managed Account test
        <input type="checkbox" name="tos" checked"false">
        I accept the <a href="https://stripe.com/us/terms"> Stripe Terms of Service</a>
      <input type="submit" value="Create">
    <% end %>
</div>
<% end %>

<%= react_component('DashboardPage', {venue_ids: @company.venues.map(&:id),
                                     company_id: @company.id,
                                     locale: I18n.locale.to_s,
                                     form_authenticity_token: form_authenticity_token,
                                     }, {}) %>

app/views/companies/update.html.erb
<h1>Companies#update</h1>
<p>Find me in app/views/companies/update.html.erb</p>